server:
  address: 0.0.0.0
  port: 8080
spring:
  application:
    name: store-app
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: bstore992@gmail.com
    password: /pRFJ+)6a?pbPY9"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  datasource:
    url: jdbc:postgresql://localhost:5432/store-db
    username: postgres
    password: root
  main:
    allow-bean-definition-overriding: true
config:
  oauth2:
    privateKey: MIIEogIBAAKCAQEAs7yIHdSkAAoRr+wq4priY/2QBoQgjC12KVkY1Zo9TX534dWtEQV4/k+BxdLG44u6XYZN2O9+mJUUZgOqkbWA5QXPubnLNyawTz/G0KYCQRVT/INGNOiRVrzSJ67aNlQ6745fDQbPG34XIzX/wioEz6xGPLxYpfL08LPz8aekvDgviHKTCkJdky8m7GojPYyVob2UWcelK2cb77HEbZpYCEZGlwmQxXGcyINhQq0bIDvWwXxzK8Dfs6iDT5fIznGekAn2JZ80KifSyd1a0CEee9TyPVLbDqUPncuI0zQIa8/yQ/Z6LMJ0vzB2x0PoUCmh/l4DffVtWsGp3Xnxl1/56wIDAQABAoIBAFU+MyhCs005eU4AKg6y+nAF0ArnGzCgVwwhL4AO2MgqFN1Mo/oQqGOkfZ2+64j7ufWlPsKGQ3pGKhh/4KOee3UjHnOtRE3x0WikjLxkH2mSnfSCpgdtzZBfmSQs710Y8aKv2TCqbAtT79FJSPVjTEjaIa2ofjqmUbje//E6WwzQpP6lwVaGHKxbYjkPTddM4xEMvu6dRNbHGpkn2ZxwmgaPRTjxx0XrZxY72tzpa2eaxDahZ1ZM1x8JlTkwW11A+sD7qnqLAvWSmoFHcJUQn4EruL/qFSZ2ItGWwEDa9o35uwSZlvCkJknmEsXyz4+2NDx763LqoRiWbXUSA2uHLcECgYEA5U3QVj2T2WuUQQGRhi0+pYlrC2MFl3755XjNLur7NPtuAwvt3lo9H10c1sf+hNeZEk31lCLN9SVtH2UmCOj1LSmyDDpPhPtMzTf6GuQ2PNqk2Pa2xqkKAtdWmk0UkFgu85d+iyRZyWX1T/sL5AEQTHIUK/wnVSH2lbxDjjY2hnECgYEAyKlnzzjHdljKqeuwrTfhyuJPeKUV3srRpqxgJ6LKcH6cLHrkFXRK1btd91cMrPl3oJQ6X3lSvep9LfY5xXNtYxGnkCAkmKCV72pN+f3L+WJ/7ObZDWQ+i8OxYych1FkkBpxac55ZfY3wtN+T1sIQF+9aZbUurFELeDAshGC6jBsCgYBulaZh0PSaqE0pRI5f/TX3M1ySc0DhHPV7e1TIyb44gQE/KuOeljpgA9HCq1TN0AQcVciXlmlpTpFf0LIVHfQPwcoCJ6Tt5xvU5KgTi/e0RWW21NS03hTb5en4JDBEpKKQC4GVrQQ4Ipm55sKHRRQNKf8cb1Cwt95pvA+AaBjHoQKBgAJ/mXtLCbC/ikZzWM/PUlBkYPjvlUYg4Fti6g+UR1D/QpKLNSvPNt9SZekefFnrAUJOlit6Jz2WHdjkp/N9bG8/WQbCX7JGzZcdi7sBHfkM8OrSNQGlreGvnhXN9u3d7kTmzXmDDzow+j5GSmDyKaEiqc16ZAphN/NXJja/vZLhAoGAQqqgvHSV5m6MOSqH+ybLqpo9pA+sL057XQBc6bAVf7YDbCM3WDWI7vHDZfrg+t2HymvXdzMei9LbIVCHFnRuypq4E2HGHaA7tqgH9dkB7kb9q/XapGZ2Do6wUJruR6/tbX/9w3TrNgRDo2PuNgkyHiWn+XAPKimWb762EXED4UI=
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs7yIHdSkAAoRr+wq4priY/2QBoQgjC12KVkY1Zo9TX534dWtEQV4/k+BxdLG44u6XYZN2O9+mJUUZgOqkbWA5QXPubnLNyawTz/G0KYCQRVT/INGNOiRVrzSJ67aNlQ6745fDQbPG34XIzX/wioEz6xGPLxYpfL08LPz8aekvDgviHKTCkJdky8m7GojPYyVob2UWcelK2cb77HEbZpYCEZGlwmQxXGcyINhQq0bIDvWwXxzK8Dfs6iDT5fIznGekAn2JZ80KifSyd1a0CEee9TyPVLbDqUPncuI0zQIa8/yQ/Z6LMJ0vzB2x0PoUCmh/l4DffVtWsGp3Xnxl1/56wIDAQAB
    tokenTimeout: 60
    resourceId: store-resource
    clientID: client
    clientSecret: secret
    accessTokenUri: http://localhost:8080/oauth/token
    userAuthorizationUri: http://localhost:8080/oauth/authorize
    resourceURI: http://localhost:8080/oauth/authorize
security:
  oauth2:
    client:
      grant-type: password
  basic:
    enabled: false
    authorize-mode: NONE
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: hediabed
    key-pair-alias: mytestkey
    key-pair-password: hediabed
    public-key: classpath:public.txt
ribbon:
  eager-load:
    enabled: true
endpoints:
  health:
    enabled: true
support:
  email: hedi.abed.0@gmail.com
logging:
  pattern:
    console: " %d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: INFO